server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
          
info:
  contact:
    email: support@ecommerce.com
    phone: 355 61 111 1111