server:
  port: 9999

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce-auth-db?createDatabaseIfNotExist=true
    username: root
    password: 1234